# Python script to create a directory for the new test "test_name" containing :		#
# - test_name.c   : an empty source file following the template of crashos test		#
# - test_name.txt : an empty file to describe the test								#
# - test_name.log : an empty file to store logs generated by the test				#
# - Makefile	  : the local Makefile to create the test_name.o      				#

import sys
import os

nb_arg = len(sys.argv)
args = sys.argv

# Check arguments
if (nb_arg != 2):
	print "Error : bad number of arguments"
	print "Usage : create_new_test_directory.py test_name"
	exit()

# Check that no directory called test_name already exists
test_name =  sys.argv[1]
test_dir = "../src/" + test_name
if os.path.exists(test_dir):
	print "Error : " + test_name + " directory already exist"
	exit()

# Create the new directory and the new files
os.mkdir(test_dir)
c_template = open ("../templates/test_template.txt")
c_file     = open(test_dir +"/" + test_name + ".c", "a")
txt_file   = open(test_dir +"/" + test_name + ".txt", "a")
log_file   = open(test_dir +"/" + test_name + ".log", "a")
make_file  = open(test_dir +"/" + "Makefile", "a")

for line in c_template.readlines():
	if "test_x" in line:
		c_file.write(line.replace("test_x", test_name))		
	else:
		c_file.write(line)

make_file.write("obj := " + test_name + ".o")

c_template.close()
c_file.close()
txt_file.close()
log_file.close()
make_file.close()

print "Directory " + test_name + " created"
